name: Build and publish container

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./proxy
          file: ./proxy/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/github-proxy:latest
            ghcr.io/${{ github.repository_owner }}/github-proxy:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=FastAPI GitHub reverse proxy

      - name: Attempt to set package visibility to public (best-effort via REST)
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Best-effort: try a few endpoints using the workflow's GITHUB_TOKEN.
          # Continue-on-error semantics are handled — do not fail the job if visibility cannot be changed.
          set -x
          BODY='{"visibility":"public"}'

          # repo-scoped endpoint
          URL1="https://api.github.com/repos/${OWNER}/${REPO}/packages/container/github-proxy/visibility"
          curl -sS -X PUT -H "Authorization: Bearer ${TOKEN}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" -d "${BODY}" "$URL1" || true

          # user-scoped endpoint
          URL2="https://api.github.com/user/packages/container/github-proxy/visibility"
          curl -sS -X PUT -H "Authorization: Bearer ${TOKEN}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" -d "${BODY}" "$URL2" || true

          # package-id endpoint (if listing returned an id)
          PKGID=$(curl -sS -H "Authorization: Bearer ${TOKEN}" -H "Accept: application/vnd.github+json" "https://api.github.com/user/packages?package_type=container" | jq -r '.[] | select(.name=="github-proxy") | .id' || true)
          if [ -n "$PKGID" ] && [ "$PKGID" != "null" ]; then
            URL3="https://api.github.com/user/packages/${PKGID}/visibility"
            curl -sS -X PUT -H "Authorization: Bearer ${TOKEN}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" -d "${BODY}" "$URL3" || true
          fi
